### ISSUE TITLE
Not an issue. Just some questions

### ISSUE THREAD

**Issue by vardelea** [SirVoRaK/chess#3] opened 2023-06-21 14:56 UTC
Hi. How do you get the images for the pieces? Is there a possibility to have different image for each pawn individually? E.g., pawn on a2 to have image A, pawn on b2 to have image B…and so on.

Thank you in advance

**Comment by rodolfoinfantini** [comment] 2023-06-21 15:18
Hi!

> How do you get the images for the pieces?

The images are stored here: [public/assets/pieces](https://github.com/SirVoRaK/chess/tree/main/public/assets/pieces)

So it creates that path based on 3 things: the selected skin, the piece color and the piece type.
For example:
A black pawn with the skin 0 selected:
Would need to access [public/assets/pieces/skin0/bP.svg](https://github.com/SirVoRaK/chess/tree/main/public/assets/pieces/skin0/bP.svg).
The method getImgSrc from [public/modules/piece.js](https://github.com/SirVoRaK/chess/blob/main/public/modules/piece.js#L259) creates that path.

> Is there a possibility to have different image for each pawn individually?

With just the current code, no.
But you can tweak the getImgSrc method, more specifically this line:
`/${colorLetter[this.color]}${typeLetter[this.type]}.svg`
as you like to get the image that you want, maybe consider the x and the y, or receive the start position as (a2,b2...) and use it to generate the image path.

**Comment by vardelea** [comment] 2023-06-21 17:20
Thank you so much. Ok, i am going to try, but you lost me already.🙂 I know this topic is not part of your project, (that btw, is incredible) but would you be able / have the time to provide more details?

**Comment by vardelea** [comment] 2023-06-23 04:20
Ok. So i cannot figure out how to receive the a1, a2…positions. I was able to add dedicated constants (like pawn1, pawn2…). This worked just fine in the means that indeed, i have all pieces with their one image. The issue is that, only the “over the board works” in this case. The puzzles and everything related to stockfish are now working anymore. I believe it has to do with the letterToType const, that is used by game.js. The fact that i have p1:, p2:…there is messing things up…but i do not know where…
So what i would need (i guess) is to somehow define that the pawn in the start position a1 will have the image1, and the pawn in start position 2 will have the image a2…and so on. But i do not know how to do that…

**Comment by rodolfoinfantini** [comment] 2023-06-26 12:17
Hey!
Take a look at this branch: [feature/img-per-piece](https://github.com/SirVoRaK/chess/tree/feature/img-per-piece)
I made some changes so it is possible to have individual imgs for each column.
The images files must follow this rule:
public/assets/pieces/skin0/wP/wP1.svg (a folder with the piece name, with the images being piece name + column .svg).
The new code tries to get this path (with the column) and if the image doesn't exist it falls back to the old path convention:
public/assets/pieces/skin0/wP.svg

I will not merge it rn, because it was not a planned feature.

**Comment by vardelea** [comment] 2023-06-27 09:25
Hi!
Do not know how to thank you enough! This is amazing!
There are few things i had to modify in order to make it work.

First thing was this: 
        const column = this.initialPosition.x + 1
        const columnBasedPath = `${pieceName}/${pieceName}${row}.svg`

Here, we see {row}. If this is the intend, maybe i am doing something wrong as it did not work for me, but when i modified it to {column}, it worked for the pawns and for the rooks and knights in columns a and b. It did not work for the other pieces.

So i added few more "initialPosition.x" properties with "-1", "-2", "-3", "-5". 
No i have all my new pieces taking the right image from their respective locations (i have created these folders wP, bP, wR, bR, wK, bK,wQ, bQ, wB, bB, wN, bN and added images in the wQ1.svg format).

Now, the game is working fine except for 2 use cases. (and these are recurring randomly)
1. When Pawn is promoting, sometimes the Queen is not one of my Queens images, but a "regular icon" queen (like the ones in skin0 for example.
2. In puzzles, sometimes (so again, randomly), instead of my images, the Queen and/or the King have "regular icons" and not my images.

Thanks again!

**Comment by rodolfoinfantini** [comment] 2023-06-27 11:46
Hey!

> Here, we see {row}. If this is the intend, maybe i am doing something wrong as it did not work for me, but when i modified it to {column}.

Thank you for the report, it was supposed to be column, I renamed the variable but didn't change the references lol.

> it worked for the pawns and for the rooks and knights in columns a and b. It did not work for the other pieces.

Here it worked for all the pawns, and for both bishop and knight. It will not _work_ for the queen and for the king, because there is always only one of them, well, it will work but it is easier to just add a default one with the old convention.

> So i added few more "initialPosition.x" properties with "-1", "-2", "-3", "-5".

Why would you need this?

> When Pawn is promoting, sometimes the Queen is not one of my Queens images, but a "regular icon" queen (like the ones in skin0 for example.

Yeah, currently it will not work, the initial position is set on the piece creation, when the pawn promotes it just changes it image and it type but doesn't recreate it.
So if a pawn from a2 promotes on b8 it will get the **1** image (from the **a** column).
A fix for this would be setting the initial position when it promotes.

> In puzzles, sometimes (so again, randomly), instead of my images, the Queen and/or the King have "regular icons" and not my images.

Well, that is very strange, didn't happen here. I'll try to reproduce.

**Comment by rodolfoinfantini** [comment] 2023-06-27 12:13
I've just commited a fix and a performance improvement to the branch!
Fixed the ghost images src (it was wrong when the piece lefts its original column).
Changed how the code checks for a valid image so is can load a lot faster.

**Comment by rodolfoinfantini** [comment] 2023-06-27 12:16
And about the puzzles:
If (in the puzzle) the king starts on **g1** it will get **7** image because the initial position of the king will be { x: 6, y: 0 } and not the usual start position, for this to work I would need to change a lot on how the puzzle works.

**Comment by vardelea** [comment] 2023-06-27 17:37
Hi!

Thanks again for all the support!
For me, something is not working well. :)

In the initial position, "my images" are not all loaded. As experienced in the previous version, if we have this:
        const column0 = this.initialPosition0.x +1
        const columnBasedPath = `${pieceName}/${pieceName}${column}.svg` // e.g. wQ/wQ1.svg

this will only load: 

- all white pawns
- all black pawns
- white rook on column a
- black rook on column a
- white knight in column b
- black knight in column b

All the others are loaded with the "old pieces icons"
So for example, the rooks on column h have the "old pieces icons"
Queen and King i understand, we can make it work by adding "my images" to the default ones.

In the previous code version, i managed to have all "my images" loaded, by adding the initialPosition.x -2/-3/-4/-5.
Example:
        const column2 = this.initialPosition2.x -1
        const columnBasedPath2 = `${pieceName}/${pieceName}${column2}.svg` // e.g. wQ/wQ1.svg

        const column3 = this.initialPosition3.x -2
        const columnBasedPath3 = `${pieceName}/${pieceName}${column3}.svg` // e.g. wQ/wQ1.svg
.........

in this version, this is not working anymore. Probably because now the function is not async anymore, but, as you may have noticed, i am no javascript expert, so i do not really know why 😀

For the promotion, it must take the image from somewhere. Can you share from where?
For the puzzles, the same. It takes the images for the queen and king from somewhere. From where? 
Are those the default ones? I have not tried that yet...
I am asking, because i can change those images...

Will it be ok to reach out to you via mail? Is the outlook one in your github contact info still available?

Thanks again!

**Comment by vardelea** [comment] 2023-06-29 13:19
Ok. I figured it out eventually. All is working now. I had to change the default icons to "my images".
No need for initialPosition.x modifications.
Thanks!

**Comment by rodolfoinfantini** [comment] 2023-06-30 18:34
Hey!
Sorry for the delay, I was busy this week.

> For the promotion, it must take the image from somewhere. Can you share from where?

It just gets the queen image

> Will it be ok to reach out to you via mail? Is the outlook one in your github contact info still available?

I've just changed the email, I was not using the outlook anymore

> Ok. I figured it out eventually. All is working now. I had to change the default icons to "my images".

Nice! Good to know. I'll close the issue if you don't have any more questions.

**Comment by vardelea** [comment] 2023-07-01 06:49
Thank you for all your support! So, in case i will need your support in the future, should i just post in here? Would that be ok?

**Comment by rodolfoinfantini** [comment] 2023-07-01 12:32
No problema at all, I'm glad to help.

> So, in case i will need your support in the future, should i just post in here?

Sure, just create another issue. I'll close this one.

**Closed as completed** 2023-07-01 12:32 UTC
Labels: question
